### ISSUE TITLE
Merging modules back into love-api

### ISSUE THREAD

**Issue by rm-code** [rm-code/love-api#3]
In a personal conversation Santos brought up some good points for having the documentation as a single file. 

Would love to hear what other people think, because for my own project (which uses the api) it doesn't matter at all.

**Comment by pkulchenko** [comment]
My slight preference would be for having one file as well, but this is not a big issue for me as I can always merge the files before processing them. I only use the files for conversion to another format (that is recognized by ZeroBrane Studio), so my requirements are probably not very representative.

**Comment by pkulchenko** [comment]
@rm-code, given that you provide `love_api.lua` file that produces the same result as the "original" love_api.lua file, I'm good with the existing structure. I just tested it with my conversion script and it works without issues.
