### ISSUE TITLE
0.10.0 Update

### ISSUE THREAD

**Issue by rm-code** [rm-code/love-api#8]
The update to [0.10.0](https://love2d.org/wiki/0.10.0) is now happening on the develop branch. It's hard to differentiate between changes which are made because of 0.10.0 or *just* concern 0.9.2. So I will treat all changes as changes towards 0.10.0.

Feel free to contribute based on the [changelog](https://love2d.org/wiki/0.10.0). 

Latest revision as of 03:15, 17 December 2015

## Additions
- [x] Added an iOS port.
- [x] Added an Android port.
- [x] Added support for reading accelerometer values on mobile devices. Accelerometers are exposed as 3-axis Joysticks.
- [x] Added the flag t.accelerometerjoystick to love.conf. Disables accelerometer-as-joystick functionality on mobile devices when false.
- [x] Added the flag t.gammacorrect to love.conf (replaces t.window.srgb.) Enabling it globally enables gamma-correct rendering, when supported.
- [x] Added video playback support for Ogg Theora videos, via love.graphics.newVideo.
- [x] Added love.video module. It is not used for displaying videos on-screen (see Video objects for that).
- [x] Added love.touch module. Note that it has important differences from the touch implementation in the LÖVE 0.9.2 Android and iOS ports.
- [x] Added love.touch.getTouches
- [x] Added love.touch.getPosition
- [x] Added love.touch.getPressure
- [x] Added love.touchpressed, love.touchreleased, and love.touchmoved.
- [x] Added love.system.vibrate.
- [x] Added love.filesystem.setRequirePath and love.filesystem.getRequirePath.
- [x] Added an optional program exit status number argument to love.event.quit.
- [x] Added love.filedropped and love.directorydropped event callback functions.
- [x] Added love.lowmemory event callback function, called when the app is running out of memory on mobile operating systems.
- [x] Added love.textedited event callback function, called when the user is compositing text (e.g. via an IME.)
- [x] Added love.wheelmoved event callback function (replaces "wu" and "wd" constants for love.mousepressed.)
- [x] Added love.mouse.hasCursor.
- [x] Added a boolean argument to love.mousepressed and love.mousereleased indicating whether the button event originated from a touch press.
- [x] Added love.keyboard.isScancodeDown.
- [x] Added optional x/y/width/height arguments to love.keyboard.setTextInput. They tell the system where text will show up so on-screen keyboards can avoid that area.
- [x] Added Source:getType (replaces Source:isStatic.)
- [x] Added Source:getDuration and Decoder:getDuration.
- [x] Added an optional string argument containing raw pixel data to the width/height variant of [[love.image.newImageData]].
- [x] Added love.graphics.ellipse.
- [x] Added rounded-rectangle support to love.graphics.rectangle.
- [x] Added love.graphics.points (replaces love.graphics.point).
- [x] Added love.graphics.intersectScissor.
- [x] Added an optional argument to love.graphics.setBlendMode which indicates whether to treat the colors of drawn objects as having pre-multiplied alpha.
- [x] Added a new built-in shader variable: "mat3 NormalMatrix".
- [x] Added love.graphics.getSupported (replaces love.graphics.isSupported.)
- [x] Added love.graphics.getSystemLimits (replaces love.graphics.getSystemLimit.)
- [x] Added love.graphics.stencil, love.graphics.setStencilTest and love.graphics.getStencilTest (replaces love.graphics.setStencil.)
- [x] Added love.graphics.isActive.
- [x] Added color arguments to love.graphics.clear. It no longer always uses the background color value.
- [x] Added love.graphics.discard.
- [x] Added love.graphics.isGammaCorrect
- [x] Added the "clampzero" WrapMode.
- [x] Added the ability to specify custom mipmaps when creating an image, via [[love.graphics.newImage]](filename, {mipmaps={mip1, mip2, ...}}).
- [x] Added optional x/y/width/height arguments to Image:refresh and Canvas:newImageData.
- [x] Added Image:getFlags.
- [x] Added one- and two-channel Canvas formats: r8, rg8, r16f, rg16f, r32f, and rg32f.
- [x] Added support for different formats in each Canvas when using multi-canvas rendering. Added the "multicanvasformats" GraphicsFeature constant.
- [x] Added support for OpenGL ES 2 and 3.
- [x] Added support for loading ETC, EAC, PVRTC and ASTC compressed textures on systems that support them.
- [x] Added custom vertex attribute support for Meshes via new variants of love.graphics.newMesh.
- [x] Added Mesh:setVertexAttribute and Mesh:getVertexAttribute.
- [x] Added Mesh:getVertexFormat.
- [x] Added an optional 'startvertex' argument to Mesh:setVertices.
- [x] Added the ability for love.graphics.newMesh and Mesh:setVertices to accept a Data object.
- [ ] Added Mesh:flush.
- [x] Added Mesh:setAttributeEnabled and Mesh:isAttributeEnabled.
- [x] Added Mesh:attachAttribute.
- [x] Added SpriteBatch:attachAttribute.
- [x] Added Shader:sendColor.
- [ ] Added new shader functions: gammaCorrectColor, gammaToLinear, and linearToGamma. The functions also have 'precise' and 'fast' variants.
- [x] Added Text objects and love.graphics.newText.
- [x] Added per-character color support to love.graphics.print, love.graphics.printf, and Text objects.
- [ ] Added BMFont bitmap font file support to love.graphics.newFont and love.font.
- [x] Added kerning support for TrueType/OpenType and BMFont Fonts.
- [ ] Added an optional font hinting argument to love.graphics.newFont when loading TrueType fonts.
- [x] Added an optional spacing argument to love.graphics.newImageFont, which applies additional spacing to all rendered glyphs.
- [x] Added Font:setFallbacks.
- [x] Added love.window.maximize.
- [x] Added love.window.close.
- [x] Added love.window.requestAttention.
- [x] Added love.window.setDisplaySleepEnabled and love.window.isDisplaySleepEnabled.
- [x] Added BezierCurve:renderSegment and BezierCurve:removeControlPoint.
- [x] Added BezierCurve:getSegment.
- [x] Added love.math.compress and love.math.decompress.
- [x] Added Channel:performAtomic.

## Removals
- [x] Removed callback variant of love.filesystem.getDirectoryItems
- [x] Removed the "wu" and "wd" constants for love.mousepressed (replaced by love.wheelmoved.)
- [x] Removed the named mouse button constants (replaced by button numbers.)
- [x] Removed Source:isStatic (replaced by Source:getType.)
- [x] Removed image loading support for all (non-compressed texture) file formats except for PNG, JPEG, TGA, and BMP.
- [x] Removed JPEG encoding support from ImageData:encode.
- [x] Removed love.graphics.point (replaced by love.graphics.points).
- [x] Removed love.graphics.setPointStyle and love.graphics.getPointStyle.
- [x] Removed love.graphics.isSupported (replaced by love.graphics.getSupported.)
- [x] Removed love.graphics.getSystemLimit (replaced by love.graphics.getSystemLimits.)
- [x] Removed love.graphics.setStencil (replaced by love.graphics.stencil and love.graphics.setStencilTest.)
- [x] Removed the "canvas", "shader", "npot", "subtractive", and "mipmap" GraphicsFeature constants (the features always have guaranteed support now.)
- [x] Removed the "multicanvas" GraphicsFeature constant (use love.graphics.getSystemLimits instead.)
- [x] Removed the "srgb" GraphicsFeature constant (use love.graphics.isGammaCorrect or love.graphics.getCanvasFormats().srgb instead.)
- [x] Removed the "srgb" flag in love.window.setMode and in the t.window table in love.conf (Replaced by t.gammacorrect.)
- [x] Removed the "premultiplied" BlendMode (love.graphics.setBlendMode("alpha", "premultiplied") now does the same thing.)
- [x] Removed Canvas:getPixel (use Canvas:newImageData instead.)
- [x] Removed Canvas:clear (use love.graphics.clear instead.)
- [x] Removed Mesh:getVertices.
- [x] Removed Mesh:setVertexColors and Mesh:hasVertexColors (use Mesh:setAttributeEnabled("VertexColor", enable) instead.)

### Functions deprecated in 0.9.x
- [x] Removed love.graphics.getMaxImageSize and love.graphics.getMaxPointSize (replaced by love.graphics.getSystemLimits.)
- [x] Removed Mesh:setImage, Mesh:getImage, SpriteBatch:setImage, SpriteBatch:getImage, ParticleSystem:setImage, and ParticleSystem:getImage (replaced by set/getTexture.)
- [x] Removed SpriteBatch:bind and SpriteBatch:unbind.
- [x] Removed Canvas:getFSAA and the "fsaa" flag in love.conf and love.window.setMode (replaced by Canvas:getMSAA and the "msaa" flag.)
- [x] Removed the "dxt" and "bc5" GraphicsFeature constants (replaced by love.graphics.getCompressedImageFormats.)
- [x] Removed the "hdrcanvas" GraphicsFeature constant (replaced by love.graphics.getCanvasFormats.)
- [x] Removed love.window.getWidth, love.window.getHeight and love.window.getDimensions (use love.graphics.getWidth, love.graphics.getHeight, love.graphics.getDimensions or love.window.getMode instead.)

## Renamed APIs
- [x] Renamed the fullscreen type "normal" to "exclusive".
- [x] Renamed the DistanceModel constants "inverse clamped", "linear clamped", and "exponent clamped" to "inverseclamped", "linearclamped", and "exponentclamped".
- [x] Renamed blend modes "additive", "subtractive", and "multiplicative" to "add", "subtract", and "multiply".
- [x] Renamed the key constant and Scancode representing the spacebar from " " to "space".
- [x] Renamed File:eof to File:isEOF.
- [x] Renamed Canvas:getImageData to Canvas:newImageData.
- [x] Renamed love.image's CompressedData type to CompressedImageData.

**Comment by Positive07** [comment]
Wow this is really nice! Could we also have a 0.8.0 branch? That would be useful too

I'll try to help but I kinda have some things to do right now but I surely will

**Comment by rm-code** [comment]
> Could we also have a 0.8.0 branch?

Sure, but what would be the benefit of that branch? 0.8.0 is heavily outdated.

**Comment by Positive07** [comment]
Well, little probably hahaha. 0.8.0 was an important release with many games released to it, and this is a documentation project, so having the information for older releases is not a bad idea (though going back even more than 0.8.0 is kinda hard and pointless)

**Comment by rm-code** [comment]
I see what you mean, but maintaining several versions would mean a lot of work. The wiki is a better place to document the whole history of LÖVE.

This API  / documentation is meant to always be up to date, so it can be used to [generate plugins](https://github.com/rm-code/love-atom), offline documentation etc. 

Therefore the 0.10.0 branch will be merged as soon as 0.10.0 is officially released.

**Comment by Positive07** [comment]
I see, well then I'll fork it and try to keep it stable (since no updates will be made to older versions, should be simple), but I understand the need of an up to date repository instead of keeping old versions so keep it like that!

Thanks!

**Comment by rm-code** [comment]
When you have the 0.8.0 doc ready feel free to submit a pull request. I don't see any harm to having it in the repository - I just don't want to maintain it myself :smile:

**Comment by Positive07** [comment]
Ohh! Okay then hahaha

PS: Keep a branch for 0.9.X even when 0.10.0 gets stable

**Comment by rm-code** [comment]
> PS: Keep a branch for 0.9.X even when 0.10.0 gets stable

I don't think a separate branch is needed since it can always be created from the last 0.9.2 version tag, right? I'm asking, because I'm thinking about merging the 0.10.0 branch into develop.

**Comment by Positive07** [comment]
Well you can't commit to a tag for example if there is a change in the format, or you cant fix errors or mystypes if there is still something

**Comment by rm-code** [comment]
Yes that's true, but you can start a branch by specifying the commit of that tag for example.

**Comment by Positive07** [comment]
And that is true too, but you are starting a branch later on, which should be the same than doing it right now... :confused: 

You get to chose, I'm not sure which way is better to tell the truth haha

**Comment by rm-code** [comment]
Added:
- [love.window.close](https://github.com/rm-code/love-api/commit/ea5b466b40f1d479ca37f8c1509486cc1fb58d5a)
- [love.graphics.isActive](https://github.com/rm-code/love-api/commit/deb7a1396916831970b269610dd6a2ec901c98fd)
- [love.system.vibrate](https://github.com/rm-code/love-api/commit/70c32a3b4d7dbd4ba5ee9a3415631cb04ae71fe3)
- [love.window.requestAttention](https://github.com/rm-code/love-api/commit/4fed713ea505529586580e77fa95aad4159732be)

**Comment by rm-code** [comment]
Added: 
- [love.math.compress](https://github.com/rm-code/love-api/commit/71b7a72dd9f1784d69b5273bd8b68af076cc14ac)
- [love.math.decompress](https://github.com/rm-code/love-api/commit/a7a255f861657561ff691bb7aa06c8a743827d11)
- [love.graphics.getSupported](https://github.com/rm-code/love-api/commit/c408d14169335c04c43c144d3cc8cb670194b8b9)
- [Shader:sendColor](https://github.com/rm-code/love-api/commit/e305b15c9595e014baf579011cd80b9f9bba2bd5)

**Comment by rm-code** [comment]
Added:
- love.graphics.stencil
- love.graphics.setStencilTest
- love.graphics.getStencilTest
- love.graphics.discard

Updated:
- love.math.compress

**Comment by rm-code** [comment]
Removed:

- love.window.getDimensions

**Comment by rm-code** [comment]
Removed:

- love.graphics.point

**Comment by rm-code** [comment]
Added:
- love.graphics.points
- Source:getDuration and Decoder:getDuration
- Decoder module
